[workspace]
resolver = "2"
members = [
    "crates/pesa-core",
    "crates/pesa-tauri",
    "crates/pesa-macros",
    "crates/pesa-axum",
    "crates/pesa-lua",
    # "crates/pesa-ratatui",
]

[workspace.package]
version = "1.2.0"
edition = "2024"
