[package]
name = "pesa-ratatui"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
pesa-core = { path = "../pesa-core" }
